// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtcjeiES-ZabMJMqgD5Vbl1IwFr5SF4HY',
    appId: '1:920059684254:android:1e071a33afade1bf62e28f',
    messagingSenderId: '920059684254',
    projectId: 'learning-academy-management',
    databaseURL: 'https://learning-academy-management-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'learning-academy-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOUcGTx6MLJp5Tw68PVJwQr5Zyt9Qxn1k',
    appId: '1:920059684254:ios:c13c185011c9d89362e28f',
    messagingSenderId: '920059684254',
    projectId: 'learning-academy-management',
    databaseURL: 'https://learning-academy-management-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'learning-academy-management.appspot.com',
    iosBundleId: 'com.example.schoolProject',
  );
}
