default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --target-platform=android-arm"
    firebase_app_distribution(
        app: "1:920059684254:android:1e071a33afade1bf62e28f",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "..\\build\\app\\outputs\\apk\\release\\app-release.apk",
        testers: "fsafisotricky62@gmail.com",
        release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
    )
  end
end